[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/log/caddy/*.log
    Tag          caddy.*
    Parser       json
    DB           /tmp/flb_caddy.db
    Mem_Buf_Limit 5MB

[OUTPUT]
    Name         loki
    Match        caddy.*
    Host         ${LOKI_HOST}
    Port         443
    TLS          On
    TLS.Verify   Off
    HTTP_User    ${LOKI_USER}
    HTTP_Passwd  ${LOKI_PASSWORD}
    Labels       job=caddy-logs, service_name=${SERVICE_NAME}
    Label_Keys   $request_host,$status
    Auto_Kubernetes_Labels off
