import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    // Auto-generate the sidebar from the folder structure of content/
    docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
